src/main/java/com/ssg/bidssgket/user/domain/product/view/ProductViewController.java
src/main/resources/static/user/css/regist.css
src/main/resources/static/user/css/style.css
src/main/resources/templates/index.html
src/main/resources/templates/user/fragments/config.html
src/main/resources/templates/user/fragments/footer.html
src/main/resources/templates/user/fragments/header.html
src/main/resources/templates/user/fragments/layout.html
src/main/resources/templates/user/product/regist.html

index page 생성

---

src/main/java/com/ssg/bidssgket/common/domain/BaseTimeAndDeleteEntity.java
src/main/java/com/ssg/bidssgket/common/domain/BaseTimeEntity.java
src/main/java/com/ssg/bidssgket/user/domain/order/domain/Parcel.java
src/main/java/com/ssg/bidssgket/user/domain/order/domain/PurchaseOrder.java
src/main/java/com/ssg/bidssgket/user/domain/order/domain/SaleOrder.java
src/main/java/com/ssg/bidssgket/user/domain/payment/domain/Pay.java
src/main/java/com/ssg/bidssgket/user/domain/payment/domain/PayChange.java
src/main/java/com/ssg/bidssgket/user/domain/payment/domain/Payment.java
src/main/java/com/ssg/bidssgket/user/domain/payment/domain/enums/PayChangeType.java

안녕하세요
Order Entity & Pay Entity 업데이트하였습니다.
감사합니다.

feat: order & pay Entity Updated

---

src/main/java/com/ssg/bidssgket/admin/api/chat/AdminChatApiController.java
src/main/java/com/ssg/bidssgket/admin/api/member/AdminMemberApiController.java
src/main/java/com/ssg/bidssgket/admin/view/admin/chat/AdminChatViewController.java
src/main/java/com/ssg/bidssgket/admin/view/admin/member/AdminMemberViewController.java
src/main/java/com/ssg/bidssgket/admin/view/admin/order/AdminOrderViewController.java
src/main/java/com/ssg/bidssgket/admin/view/admin/payment/AdminPaymentViewController.java
src/main/resources/templates/admin/content/pages/chat/chat-list.html
src/main/resources/templates/admin/content/pages/member/member-info.html
src/main/resources/templates/admin/content/pages/member/member-list.html
src/main/resources/templates/admin/content/pages/member/member-report-info.html
src/main/resources/templates/admin/content/pages/member/member-report-list.html
src/main/resources/templates/admin/content/pages/payment/payment-list.html
src/main/resources/templates/admin/content/pages/product/product-list.html
src/main/resources/templates/admin/content/pages/product/product-listttetetetet.html
src/main/resources/templates/admin/layout/default_layout.html

admin front 개발
- 회원 목록
- 회원 신고 목록
- 상품 목록
- 채팅 목록
- 결제내역 목록
- 주문내역 목록

Admin front 개발

---

src/main/java/com/ssg/bidssgket/user/domain/member/domain/ChatContent.java
src/main/java/com/ssg/bidssgket/user/domain/member/domain/ChatImage.java
src/main/java/com/ssg/bidssgket/user/domain/member/domain/ChatRoom.java
src/main/java/com/ssg/bidssgket/user/domain/member/domain/Member.java
src/main/java/com/ssg/bidssgket/user/domain/member/domain/Review.java
src/main/java/com/ssg/bidssgket/user/domain/member/domain/WishList.java
src/main/java/com/ssg/bidssgket/user/domain/member/view/DTO/MemberDto.java
src/main/java/com/ssg/bidssgket/user/domain/product/domain/Product.java
src/main/java/com/ssg/bidssgket/user/domain/product/view/dto/request/ProductReqDto.java

Product, Member Entity 수정

---

src/main/java/com/ssg/bidssgket/user/domain/main/view/mainViewController.java
src/main/resources/static/user/css/style.css
src/main/resources/templates/user/fragments/config.html
src/main/resources/templates/user/fragments/header.html
src/main/resources/templates/user/main/mainpage.html

메인 페이지 html 수정

---

src/main/java/com/ssg/bidssgket/user/domain/order/view/OrderViewController.java
src/main/java/com/ssg/bidssgket/user/domain/order/view/PurchaseOrderViewController.java
src/main/java/com/ssg/bidssgket/user/domain/order/view/SaleOrderViewController.java
src/main/java/com/ssg/bidssgket/user/domain/payment/view/PaymentViewController.java
src/main/resources/templates/user/fragments/header.html
src/main/resources/templates/user/order/checkout.html
src/main/resources/templates/user/order/mypage.html
src/main/resources/templates/user/order/purchases/cancelled.html
src/main/resources/templates/user/order/purchases/completed.html
src/main/resources/templates/user/order/purchases/delivered.html
src/main/resources/templates/user/order/purchases/history/auction.html
src/main/resources/templates/user/order/purchases/history/completed.html
src/main/resources/templates/user/order/purchases/history/progress.html
src/main/resources/templates/user/order/purchases/pending.html
src/main/resources/templates/user/order/purchases/shipping.html
src/main/resources/templates/user/order/sales/cancelled.html
src/main/resources/templates/user/order/sales/completed.html
src/main/resources/templates/user/order/sales/delivered.html
src/main/resources/templates/user/order/sales/history/auction.html
src/main/resources/templates/user/order/sales/history/completed.html
src/main/resources/templates/user/order/sales/history/progress.html
src/main/resources/templates/user/order/sales/pending.html
src/main/resources/templates/user/order/sales/shipping.html
src/main/resources/templates/user/payment/deposit.html
src/main/resources/templates/user/payment/info.html
src/main/resources/templates/user/payment/withdrawal.html

안녕하세요.
1. Order & Payment 화면 html 작성 및 페이지 연결했습니다.
2. Main 페이지에서 header에 있는 "마이페이지" 버튼을 통해 이동할 수 있도록 연결했습니다.
(url: user/order/mypage)
감사합니다.

feat:order-payment Order & Payment 화면 작성 및 페이지 연결

---

src/main/resources/templates/user/order/purchases/completed.html
src/main/resources/templates/user/order/purchases/delivered.html
src/main/resources/templates/user/order/purchases/history/auction.html
src/main/resources/templates/user/order/purchases/history/completed.html
src/main/resources/templates/user/order/purchases/history/progress.html
src/main/resources/templates/user/order/purchases/pending.html
src/main/resources/templates/user/order/purchases/shipping.html
src/main/resources/templates/user/order/sales/history/auction.html
src/main/resources/templates/user/order/sales/history/completed.html
src/main/resources/templates/user/order/sales/history/progress.html
src/main/resources/templates/user/payment/info.html

안녕하세요.
1. order HTML의 CSS 연결 링크 삭제했습니다.
2. payment HTML의 CSS 연결 링크 삭제했습니다.
확인 부탁드립니다.
감사합니다.

feat:order-payment HTML & CSS 수정

---

src/main/java/com/ssg/bidssgket/user/domain/auction/domain/repository/AuctionRepository.java
src/main/java/com/ssg/bidssgket/user/domain/main/view/mainViewController.java
src/main/java/com/ssg/bidssgket/user/domain/product/api/ProductApiController.java
src/main/java/com/ssg/bidssgket/user/domain/product/api/dto/request/RegistProductReqDto.java
src/main/java/com/ssg/bidssgket/user/domain/product/application/ProductService.java
src/main/java/com/ssg/bidssgket/user/domain/product/domain/repository/ProductRepository.java
src/main/java/com/ssg/bidssgket/user/domain/product/view/ProductViewController.java
src/main/resources/templates/user/auction/auctionMain.html
src/main/resources/templates/user/fragments/header.html
src/main/resources/templates/user/main/mainpage.html
src/main/resources/templates/user/product/detailAuction.html
src/main/resources/templates/user/product/detailBuyer.html
src/main/resources/templates/user/product/detailSeller.html
src/main/resources/templates/user/product/list.html
src/main/resources/templates/user/product/register.html

- 상품 상세 조회(구매자,판매자,경매입찰자)
- 상품 검색
- 상품 삭제
- 카테고리별 상품 조회

Feature: 상품 상세 조회

---

src/main/java/com/ssg/bidssgket/global/config/WebSecurityConfig.java
src/main/resources/application.yml

fix: static path security 추가

---

src/main/java/com/ssg/bidssgket/global/config/WebSecurityConfig.java
src/main/resources/templates/user/main/mainpage.html

fix: main.html 이미지 제거, static path security 수정

fix: main.html 이미지 제거, static path security 수정

---

src/main/java/com/ssg/bidssgket/user/domain/eventAuction/api/EventAuctionApiController.java
src/main/java/com/ssg/bidssgket/user/domain/eventAuction/application/EventAuctionService.java
src/main/java/com/ssg/bidssgket/user/domain/eventAuction/view/EventAuctionViewController.java
src/main/java/com/ssg/bidssgket/user/domain/main/view/mainViewController.java
src/main/java/com/ssg/bidssgket/user/domain/product/api/dto/request/RegistProductReqDto.java
src/main/java/com/ssg/bidssgket/user/domain/product/domain/Acceptance.java
src/main/java/com/ssg/bidssgket/user/domain/product/domain/repository/ProductRepository.java
src/main/java/com/ssg/bidssgket/user/domain/product/view/ProductViewController.java
src/main/resources/static/user/css/style.css
src/main/resources/templates/user/eventAuction/bidFailed.html
src/main/resources/templates/user/eventAuction/bidSuccess.html
src/main/resources/templates/user/eventAuction/detailAuction.html
src/main/resources/templates/user/eventAuction/detailBuyer.html
src/main/resources/templates/user/eventAuction/detailSeller.html
src/main/resources/templates/user/eventAuction/lists.html
src/main/resources/templates/user/eventAuction/regist.html
src/main/resources/templates/user/fragments/header.html

Feat: 이벤트경매

---

src/main/java/com/ssg/bidssgket/user/domain/auction/application/AuctionService.java
src/main/java/com/ssg/bidssgket/user/domain/auction/view/AuctionViewController.java
src/main/java/com/ssg/bidssgket/user/domain/auction/view/dto/FailedProductReqDto.java
src/main/java/com/ssg/bidssgket/user/domain/product/application/ProductService.java
src/main/resources/static/user/auction/css/bidfailedupdate.css
src/main/resources/templates/user/auction/auctionregistmodify.html
src/main/resources/templates/user/auction/bidfailedupdate.html
src/main/resources/templates/user/product/bidFailed.html
src/main/resources/templates/user/product/detailAuction.html
src/main/resources/templates/user/product/detailBuyer.html
src/main/resources/templates/user/product/detailSeller.html

경매 종료 후 유찰 상태
[판매자]
- 유찰 상품 판매 재등록 혹은 삭제
- 상품 재등록시 입찰 시작 날짜, 종료 날짜 둘 다 수정 가능
- 상품 재등록 시 판매 상태 변경(ProductService에 메소드 추가)
[낙찰자]
- 낙찰 시 포기 혹은 확정
#28 유찰된 상품 처리 이슈

Feature/auction 유찰 상태 처리

---

src/main/java/com/ssg/bidssgket/user/domain/auction/application/AuctionService.java
src/main/java/com/ssg/bidssgket/user/domain/auction/domain/repository/AuctionRepository.java
src/main/java/com/ssg/bidssgket/user/domain/auction/view/AuctionViewController.java
src/main/java/com/ssg/bidssgket/user/domain/product/view/ProductViewController.java
src/main/resources/templates/user/product/bidFailed.html
src/main/resources/templates/user/product/detailAuction.html
src/main/resources/templates/user/product/detailSeller.html

- 입찰 삭제 후 메인 화면에서 들어갈 시 잘못되 페이지 이동 조건 수정

Feature/경매 경매 조건 수정

---

src/main/generated/com/ssg/bidssgket/user/domain/member/domain/QMember.java
src/main/generated/com/ssg/bidssgket/user/domain/order/domain/QDeliveryAddress.java
src/main/generated/com/ssg/bidssgket/user/domain/product/domain/QProduct.java
src/main/java/com/ssg/bidssgket/admin/api/product/auction/repository/AdminAuctionRepository.java
src/main/java/com/ssg/bidssgket/admin/api/product/auction/service/AdminAuctionService.java
src/main/java/com/ssg/bidssgket/admin/api/product/product/repository/AdminProductRepository.java
src/main/java/com/ssg/bidssgket/admin/notification/NotificationService.java
src/main/java/com/ssg/bidssgket/user/domain/auction/application/AuctionService.java
src/main/java/com/ssg/bidssgket/user/domain/auction/view/AuctionViewController.java
src/main/java/com/ssg/bidssgket/user/domain/product/view/ProductViewController.java
src/main/java/com/ssg/bidssgket/user/domain/productwish/view/WishSelectViewController.java

fix: Bean 주입 수정

---

src/main/java/com/ssg/bidssgket/admin/notification/NotificationController.java
src/main/java/com/ssg/bidssgket/admin/notification/NotificationService.java
src/main/java/com/ssg/bidssgket/user/domain/auction/view/AuctionViewController.java
src/main/resources/templates/user/main/mainpage.html

fix: noti 수정

---

src/main/java/com/ssg/bidssgket/user/domain/payment/exception/GlobalExceptionHandler.java
src/main/java/com/ssg/bidssgket/user/domain/product/view/ProductViewController.java
src/main/resources/application.yml

fix: max-file-size 수정, GlobalExceptionHandler 수정

fix: max-file-size 수정, GlobalExceptionHandler 수정

---

src/main/java/com/ssg/bidssgket/admin/notification/NotificationController.java
src/main/resources/templates/user/product/bidFailed.html
src/main/resources/templates/user/product/bidSuccess.html
src/main/resources/templates/user/product/update.html

fix: noti 경로 수정

---

src/main/resources/templates/user/eventAuction/detailBuyer.html
src/main/resources/templates/user/eventAuction/detailSeller.html
src/main/resources/templates/user/product/detailAuction.html
src/main/resources/templates/user/product/detailBuyer.html

develop 브랜치 최신화

---

src/main/java/com/ssg/bidssgket/global/config/StringToIntegerConverter.java
src/main/java/com/ssg/bidssgket/global/config/WebMvcConfig.java
src/main/java/com/ssg/bidssgket/user/domain/payment/view/PaymentViewController.java
src/main/java/com/ssg/bidssgket/user/domain/product/api/ProductApiController.java
src/main/java/com/ssg/bidssgket/user/domain/product/api/dto/request/RegistProductReqDto.java
src/main/resources/templates/user/auction/auctionMain.html
src/main/resources/templates/user/eventAuction/detailBuyer.html
src/main/resources/templates/user/eventAuction/detailSeller.html
src/main/resources/templates/user/eventAuction/lists.html
src/main/resources/templates/user/eventAuction/regist.html
src/main/resources/templates/user/main/mainpage.html
src/main/resources/templates/user/payment/checkout.html
src/main/resources/templates/user/product/bidSuccess.html
src/main/resources/templates/user/product/category.html
src/main/resources/templates/user/product/detailAuction.html
src/main/resources/templates/user/product/detailBuyer.html
src/main/resources/templates/user/product/detailSeller.html
src/main/resources/templates/user/product/list.html
src/main/resources/templates/user/product/register.html

[Fix / UI] 조회 ui 수정 & 결제 연결

---

src/main/java/com/ssg/bidssgket/user/domain/auction/application/AuctionService.java
src/main/java/com/ssg/bidssgket/user/domain/auction/domain/repository/AuctionRepository.java
src/main/java/com/ssg/bidssgket/user/domain/eventAuction/view/EventAuctionViewController.java
src/main/java/com/ssg/bidssgket/user/domain/product/view/ProductViewController.java
src/main/resources/static/user/product/css/regist.css
src/main/resources/templates/user/eventAuction/regist.html
src/main/resources/templates/user/order/purchases/history/auction.html
src/main/resources/templates/user/order/purchases/history/completed.html
src/main/resources/templates/user/order/purchases/history/progress.html
src/main/resources/templates/user/order/sales/history/auction.html
src/main/resources/templates/user/order/sales/history/completed.html
src/main/resources/templates/user/order/sales/history/progress.html
src/main/resources/templates/user/product/register.html
src/main/resources/templates/user/product/update.html

fix: 경매Repo 수정

---

src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/controller/ChatController.java
src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/repository/ChatRoomRepository.java

fix:chat수정

---

src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/controller/ChatController.java
src/main/java/com/ssg/bidssgket/user/domain/order/view/OrderViewController.java
src/main/java/com/ssg/bidssgket/user/domain/order/view/PurchaseOrderViewController.java
src/main/java/com/ssg/bidssgket/user/domain/order/view/SaleOrderViewController.java
src/main/java/com/ssg/bidssgket/user/domain/payment/view/PaymentViewController.java
src/main/java/com/ssg/bidssgket/user/domain/product/view/ProductViewController.java

최종 배포 2차시도

---

src/main/resources/application.yml

최종 배포 3차시도

---

src/main/java/com/ssg/bidssgket/user/domain/auction/application/AuctionService.java
src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/controller/ChatController.java
src/main/java/com/ssg/bidssgket/user/domain/payment/view/PaymentViewController.java
src/main/resources/templates/user/product/bidFailed.html
src/main/resources/templates/user/product/bidSuccess.html

Fix : 실시간 경매 수정

---

src/main/java/com/ssg/bidssgket/user/domain/payment/api/service/KakaoPayService.java
src/main/resources/application.yml

최종배포 7차 시도

---

.github/workflows/deploy-ncp.yml
src/main/java/com/ssg/bidssgket/global/config/WebSecurityConfig.java
src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/controller/ChatController.java
src/main/java/com/ssg/bidssgket/user/domain/payment/api/service/KakaoPayService.java
src/main/resources/application.yml
src/main/resources/templates/user/eventAuction/detailBuyer.html
src/main/resources/templates/user/eventAuction/detailSeller.html

최종 배포 9차 시도

---

src/main/java/com/ssg/bidssgket/global/config/WebSecurityConfig.java
src/main/java/com/ssg/bidssgket/user/domain/eventAuction/WebSocketConfig.java
src/main/resources/templates/user/eventAuction/detailBuyer.html
src/main/resources/templates/user/eventAuction/detailSeller.html
src/main/resources/templates/user/member/chat.html
src/main/resources/templates/user/member/info.html

최종 배포 9차시도
